# <CENTER>CLIFF WALKING

### <I> IMPORTING LIBRARIES

In [1]:
import gym
import numpy as np
import random
import time
from IPython.display import clear_output
import cv2

### <I> CREATING ENVIRONMENT

In [2]:
env=gym.make('CliffWalking-v0',render_mode='rgb_array')

### <i> Q TABLE

In [3]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n

print('No of actions: ',action_space_size,'\nNo of states: ',state_space_size)

No of actions:  4 
No of states:  48


In [4]:
q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### <I>TRAINING

In [5]:
num_episodes=10000
max_steps_per_episode=300
learning_rate=0.1
discount_rate=0.99
exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

##### 1) Q-LEARNING

In [6]:
rewards_all_episodes=[]


for episode in range(num_episodes):
    
    state=env.reset()[0]
    terminated=False
    rewards_current_episode=0
    
    for step in range(max_steps_per_episode):
        
        exploration_rate_threshold=random.random()
        if exploration_rate_threshold>exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample() 
            
        new_state,reward,terminated,truncated,info=env.step(action)
        
        #Updating Q-Table
        q_table[state][action]=q_table[state][action]*(1-learning_rate)+learning_rate*(reward+discount_rate*np.max(q_table[new_state]))
        
        
        state=new_state
        rewards_current_episode+=reward
        
        if terminated or truncated:
            break
    
    # Updating Exploration rate
    exploration_rate=min_exploration_rate+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
    
rewards_per_1000_episodes=np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print('AVERAGE PER 1000 EPISODES')
for r in rewards_per_1000_episodes:
    print('\n',count,' : ',str(sum(r/1000)))
    count+=1000

C:\Users\Niteesh\anaconda3\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


AVERAGE PER 1000 EPISODES

 1000  :  -1059.5059999999985

 2000  :  -132.41200000000026

 3000  :  -43.21100000000002

 4000  :  -27.52400000000061

 5000  :  -18.779000000000167

 6000  :  -17.204000000000015

 7000  :  -16.426999999999975

 8000  :  -16.575999999999944

 9000  :  -17.277000000000026

 10000  :  -15.389999999999926


In [34]:
rewards_per_1000_episodes

[array([-2180, -1586, -2081, -2774, -2675, -2081,  -992, -2576,  -992,
        -1982, -2576, -2873, -1685,  -439, -2180, -1487, -1883, -1190,
        -2378, -2081, -1784, -3269, -2477,  -695,  -992, -2972, -2873,
        -2477, -1784, -2675, -1982, -2180, -1190, -1289, -1784, -1177,
        -1623, -3962, -2279, -2675, -2477, -2576, -1586, -2576, -1487,
        -1289, -3071, -1982, -1388, -1586, -1883, -2081, -2081, -1982,
        -1487, -3863, -1982, -1784, -2675, -1883, -3665, -1883, -1190,
        -1388, -1388, -1586, -1388,  -497, -2576, -2873, -2180,  -992,
        -1883, -1586, -1586, -1685, -1685, -1685, -1685, -1388, -2279,
         -992, -1685, -2180, -1388, -1586,  -733, -2477, -2180, -3170,
         -794, -2279, -1883, -1388, -2081, -2675,  -794, -1289, -1487,
        -1883, -2081, -2378, -1784,  -364, -1289,  -893,  -459, -1586,
        -1289, -1289, -2477, -1784, -1685, -1289, -1388, -2279, -2675,
         -893, -1091, -2873, -1982, -1982,  -893, -1190,  -893, -2477,
      

##### 2) SARSA

In [6]:
rewards_all_episodes=[]

def choose_action(state):
    exploration_rate_threshold=random.random()
    if exploration_rate_threshold>exploration_rate:
        action=np.argmax(q_table[state,:])
    else:
        action=env.action_space.sample()
    return action


for episode in range(num_episodes):
    
    state=env.reset()[0]
    terminated=False
    rewards_current_episode=0
    
    action=choose_action(state) 
    
    for step in range(max_steps_per_episode):
            
        new_state,reward,terminated,truncated,info=env.step(action)
        
        new_action=choose_action(new_state) 
        
        #Updating Q-Table
        q_table[state][action]=q_table[state][action]*(1-learning_rate)+learning_rate*(reward+discount_rate*q_table[new_state][new_action])
        
        
        state=new_state
        action=new_action
        rewards_current_episode+=reward
        
        if terminated or truncated:
            break
    
    # Updating Exploration rate
    exploration_rate=min_exploration_rate+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
    
rewards_per_1000_episodes=np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print('AVERAGE PER 1000 EPISODES')
for r in rewards_per_1000_episodes:
    print('\n',count,' : ',str(sum(r/1000)))
    count+=1000

C:\Users\Niteesh\anaconda3\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


AVERAGE PER 1000 EPISODES

 1000  :  -573.5889999999977

 2000  :  -34.41599999999989

 3000  :  -20.989999999999828

 4000  :  -19.188999999999826

 5000  :  -18.002999999999822

 6000  :  -17.546999999999812

 7000  :  -17.752999999999812

 8000  :  -17.4869999999998

 9000  :  -17.477999999999813

 10000  :  -17.703999999999798


In [8]:
rewards_per_1000_episodes

[array([-3468, -3567, -3270, -4557, -4557, -2775, -3864, -4458, -2379,
        -3270, -3567, -2775, -3072, -2181, -2577, -3270, -1488, -3765,
        -2379, -4557, -3666, -3369, -4656, -2775, -2676, -2379, -3468,
        -2676, -2478, -2181, -2676, -1785, -1389, -2973, -2478, -2379,
        -2181, -3171, -2082, -3171, -2676, -2181, -2973, -2379, -3963,
        -2280, -2379, -3567, -3270, -1686, -2577, -1884, -2280, -1785,
        -2082, -2478, -3765, -2082, -2577, -3171, -2379, -3567, -1884,
        -3369, -1686, -2082, -2379, -2478, -2379, -1290, -3963, -2577,
        -1983,  -795, -1488, -1983, -2082, -4161, -2379, -2775, -3270,
        -3963, -2082, -3270, -1488, -1686, -3468, -3270, -3270, -1488,
        -2577, -2676, -1983, -1327, -2329, -2280, -1290, -3369, -3072,
        -1686, -2379, -1092, -1401, -2577, -1983, -2775, -1884, -2775,
        -1290, -2181, -2082, -1884, -1092, -2181, -3369, -1884, -1884,
        -1191,  -701, -3072, -1488, -1488,  -813, -1686, -2082, -1140,
      

### <I>VISUALIZATION

In [7]:
for episodes in range(3):
    state=env.reset()[0]
    terminated=False
    print('EPISODE: ',episodes+1,'\n')
    time.sleep(1)
    for step in range(max_steps_per_episode):

        img=env.render()
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
        cv2.imshow('CliffWalking',img_rgb)
        if cv2.waitKey(25) & 0xFF == ord('q'): 
            break
        time.sleep(0.3)

        action=np.argmax(q_table[state])
        new_state,reward,terminated,truncated,info=env.step(action)
        
        if terminated or truncated:
            img=env.render()
            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
            cv2.imshow('CliffWalking',img_rgb)
            if cv2.waitKey(25) & 0xFF == ord('q'): 
                break
                
            if reward==-100:
                print('You fell off the cliff!!')
                time.sleep(3)
                
            else:
                print('You reached the goal!!!')
                time.sleep(3)
                
            
            clear_output(wait=True)
            break
        
        
        state=new_state


cv2.destroyAllWindows()         
env.close()

EPISODE:  3 

You reached the goal!!!
